{
 "title": "golang runtime metrics",
 "description": "golang runtime metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "data source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(go_memstats_alloc_bytes, namespace)"
    }
   },
   {
    "name": "env_name",
    "label": "env",
    "query": {
     "query": "label_values(go_memstats_alloc_bytes, env_name)"
    }
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(go_memstats_alloc_bytes, app)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(go_memstats_alloc_bytes, server)"
    }
   }
  ]
 },
 "panels": [
  { "title": "golang runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "go_cpu_count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_cpu_count{namespace=~\"${namespace}\",env_name=~\"${env_name}\",app=~\"${app}\",server=~\"${server}\"})",
     "legendFormat": "cpu count"
    },
    {
     "expr": "sum(go_gomaxprocs{namespace=~\"${namespace}\",env_name=~\"${env_name}\",app=~\"${app}\",server=~\"${server}\"})",
     "legendFormat": "go_gomaxprocs"
    },
    {
     "expr": "sum(go_goroutines{namespace=~\"${namespace}\",env_name=~\"${env_name}\",app=~\"${app}\",server=~\"${server}\"})",
     "legendFormat": "go_goroutines"
    },
    {
     "expr": "sum(go_threads{namespace=~\"${namespace}\",env_name=~\"${env_name}\",app=~\"${app}\",server=~\"${server}\"})",
     "legendFormat": "go_threads"
    }
   ]
  },
  {
   "title": "go_info",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (version) (go_info{namespace=~\"${namespace}\",env_name=~\"${env_name}\",app=~\"${app}\",server=~\"${server}\"})",
     "legendFormat": "version: {{version}}"
    },
    {
     "expr": "go_info_ext{namespace=~\"${namespace}\",env_name=~\"${env_name}\",app=~\"${app}\",server=~\"${server}\"}",
     "legendFormat": "compiler: {{compiler}}"
    },
    {
     "expr": "go_info_ext{namespace=~\"${namespace}\",env_name=~\"${env_name}\",app=~\"${app}\",server=~\"${server}\"}",
     "legendFormat": "GOARCH: {{GOARCH}}"
    },
    {
     "expr": "go_info_ext{namespace=~\"${namespace}\",env_name=~\"${env_name}\",app=~\"${app}\",server=~\"${server}\"}",
     "legendFormat": "GOOS: {{GOOS}}"
    }
   ]
  },
  {
   "title": "metrics_push_interval_seconds",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by () (metrics_push_interval_seconds{namespace=~\"${namespace}\",env_name=~\"${env_name}\",app=~\"${app}\",server=~\"${server}\"})",
     "legendFormat": "metrics_push_interval_seconds"
    }
   ]
  },
  {
   "title": "go_memstats_alloc_bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by () (go_memstats_alloc_bytes{namespace=~\"${namespace}\",env_name=~\"${env_name}\",app=~\"${app}\",server=~\"${server}\"})"
    }
   ]
  },
  {
   "title": "go_memstats_buck_hash_sys_bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max by () (go_memstats_buck_hash_sys_bytes{namespace=~\"${namespace}\",env_name=~\"${env_name}\",app=~\"${app}\",server=~\"${server}\"})"
    }
   ]
  },
  {
   "title": "go_memstats_alloc_bytes_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by () (increase(go_memstats_alloc_bytes_total{namespace=~\"${namespace}\",env_name=~\"${env_name}\",app=~\"${app}\",server=~\"${server}\"}[1m]))"
    }
   ]
  },
  {
   "title": "go_memstats_frees_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by () (increase(go_memstats_frees_total{namespace=~\"${namespace}\",env_name=~\"${env_name}\",app=~\"${app}\",server=~\"${server}\"}[1m]))"
    }
   ]
  },
  {
   "title": "metrics_push_duration_seconds_bucket",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (le) (increase(label_replace(metrics_push_duration_seconds_bucket{namespace=~\"${namespace}\",env_name=~\"${env_name}\",app=~\"${app}\",server=~\"${server}\"}, \"le\", \"$1\",\"vmrange\", \"([^\\\\n]+)\\\\.\\\\.\\\\.([^\\\\n]+)\")[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "metrics_push_block_size_bytes_bucket",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by (le) (increase(label_replace(metrics_push_block_size_bytes_bucket{namespace=~\"${namespace}\",env_name=~\"${env_name}\",app=~\"${app}\",server=~\"${server}\"}, \"le\", \"$1\",\"vmrange\", \"([^\\\\n]+)\\\\.\\\\.\\\\.([^\\\\n]+)\")[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "go_cgo_calls_count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by () (increase(go_cgo_calls_count{namespace=~\"${namespace}\",env_name=~\"${env_name}\",app=~\"${app}\",server=~\"${server}\"}[1m]))"
    }
   ]
  },
  {
   "title": "metrics_push_total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by () (increase(metrics_push_total{namespace=~\"${namespace}\",env_name=~\"${env_name}\",app=~\"${app}\",server=~\"${server}\"}[1m]))"
    },
    {
     "expr": "sum by () (increase(metrics_push_errors_total{namespace=~\"${namespace}\",env_name=~\"${env_name}\",app=~\"${app}\",server=~\"${server}\"}[1m]))"
    }
   ]
  }
 ]
}